### PR TITLE
Switching from requests to aiohttp

### PR DESCRIPTION
**Pull request by kyriog**
I'm offering this PR for switching from requests to aiohttp to add asyncio compatibility with this lib, as requested by #7 (and my personal needs).

Please note this is currently a work in progress, the scripts part haven't been updated yet as well as the tests, which will require to change the betamax dependency (because betamax is compatible only with requests).

I just wanted to share what I've already done, and wanted to know if you're interested by this kind of change.

## How to use?

Here's some code example:

```python
async def main():
    try:
        auth_mgr = await AuthenticationManager.from_file('tokens.json')
    except FileNotFoundError:
        auth_mgr = await AuthenticationManager.create()
        auth_mgr.email_address = "pyxb-testing@outlook.com"
        auth_mgr.password = "password"
    await auth_mgr.authenticate()
    await auth_mgr.close()  # required to properly close aiohttp.ClientSession

    client = await XboxLiveClient.create(auth_mgr.userinfo.userhash, auth_mgr.xsts_token.jwt, auth_mgr.userinfo.xuid)
    profile = await client.profile.get_profile_by_xuid("2669321029139235")
    profile = await profile.json()
    print(profile)

    achievements = await client.achievements.get_achievements_xboxone_gameprogress("2669321029139235", 219630713)
    achievements = await achievements.json()
    print(achievements)

    await client.close()  # required to properly close aiohttp.ClientSession

asyncio.run(main())
```

### CODE REVIEW

**Comment by tuxuser** [comment]
This looks good and I would be happy to merge it once completed.

For replacing betamax, this looks like a worthy successor: https://pypi.org/project/vcrpy/

**Comment by kyriog** [comment]
Hey @tuxuser, thanks for your response and sorry for my inactivity about this.

I’ve started to adapt the unit tests to my aiohttp dev, and I am able to fix the "No match for the request" error by replacing `%2C` by `,` (a comma) in converted cassettes.

I’ll finish converting unit testing to aiohttp then I’ll add the commits to this PR.

**Comment by tuxuser** [comment]
Perfect, thanks!

**Comment by tuxuser** [comment]
Closing in favor of #29

**Pull request closed without merging**
